DEFAULT_TICKERS = ['AAPL', 'MSFT', 'AMZN', 'GOOGL', 'META', 'TSLA', 'NVDA', 'V']

FORECAST_DAYS = 10
HISTORY_PERIOD = '5y'
SEQUENCE_LENGTH = 90
MODEL_EXPIRY_DAYS = 7
INVESTMENT_AMOUNT = 10000

MODELS_FOLDER = 'saved_models'
TAHMIN_FOLDER = 'tahmin'

RSI_WINDOW = 14
BOLLINGER_WINDOW = 20
BOLLINGER_STD = 3

LSTM_UNITS_1 = 100
LSTM_UNITS_2 = 100
LSTM_UNITS_3 = 50
DROPOUT_RATE = 0.2
EPOCHS = 50
BATCH_SIZE = 32
VALIDATION_SPLIT = 0.2

STRONG_BUY_THRESHOLD = 10
BUY_THRESHOLD = 5
LIGHT_BUY_THRESHOLD = 2
STRONG_SELL_THRESHOLD = -10
SELL_THRESHOLD = -5
LIGHT_SELL_THRESHOLD = -2

RSI_OVERBOUGHT = 70
RSI_OVERSOLD = 30

VOLATILITY_THRESHOLD = 0.03

OPENAI_KEY = None
TELEGRAM_KEY = None
